#!/bin/bash
#
# Copyright (c) 2023, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# BioNeMo Models
# NGC Paths:
ESM1NV_MODEL="nvidian/clara-lifesciences/esm1nv:23.06"
PROTT5NV_MODEL="nvidian/clara-lifesciences/prott5nv:23.06"
MEGAMOLBART_MODEL="nvidian/clara-lifesciences/megamolbart:23.06"
EQUIDOCK_DIPS_MODEL="nvidian/clara-lifesciences/equidock:dips.23.10"
EQUIDOCK_DB5_MODEL="nvidian/clara-lifesciences/equidock:db5.23.10"
DIFFDOCK_SCORE_MODEL="nvidian/clara-lifesciences/diffdock:paper_score.23.08"
DIFFDOCK_CONFIDENCE_MODEL="nvidian/clara-lifesciences/diffdock:paper_confidence.23.08"
ESM2NV_650M_MODEL="nvidian/cvai_bnmo_trng/esm2nv650m:1.0-rc1" #TODO: update path when model is released
ESM2NV_3B_MODEL="nvidian/cvai_bnmo_trng/esm2nv3b:1.0-rc1" #TODO: update path when model is released
OPENFOLD_INH_FINETUNED_MODEL="nvidian/cvai_bnmo_trng/openfold:finetuning_pub_0.1.0" # TODO: update path and tag once released

# PBSS Paths:
ESM1NV_MODEL_PBSS="s3://bionemo-ci/models/esm1nv.nemo"
PROTT5NV_MODEL_PBSS="s3://bionemo-ci/models/prott5nv.nemo"
MEGAMOLBART_MODEL_PBSS="s3://bionemo-ci/models/megamolbart.nemo"
EQUIDOCK_DIPS_MODEL_PBSS="s3://bionemo-ci/models/equidock_dips.nemo"
EQUIDOCK_DB5_MODEL_PBSS="s3://bionemo-ci/models/equidock_db5.nemo"
DIFFDOCK_SCORE_MODEL_PBSS="s3://bionemo-ci/models/diffdock_score.nemo"
DIFFDOCK_CONFIDENCE_MODEL_PBSS="s3://bionemo-ci/models/diffdock_confidence.nemo"
ESM2NV_650M_MODEL_PBSS="s3://bionemo-ci/models/esm2nv_650M_converted.nemo"
ESM2NV_3B_MODEL_PBSS="s3://bionemo-ci/models/esm2nv_3B_converted.nemo"
OPENFOLD_INH_FINETUNED_MODEL_PBSS="s3://bionemo-ci/models/openfold.nemo"