defaults:
  - pretrain_small_span_aug

restore_from_path: /model/molecule/megamolbart/megamolbart.nemo # used when starting from a .nemo file
trainer:
  devices: 1
  num_nodes: 1
  max_epochs: 1 # PTL default. In practice we don't usually train for more than 1 epoch.
  max_steps: 500 # consumed_samples = global_step * micro_batch_size * data_parallel_size * accumulate_grad_batches
  val_check_interval: 50
  limit_val_batches: 1
  accumulate_grad_batches: 1
    
model:
  micro_batch_size: 4
  global_batch_size: 4
  data:
    dataset_path: ${oc.env:PROJECT_MOUNT}/examples/tests/test_data/molecule/ # parent directory for data, contains train / val / test folders
    dataset: # inclusive range of data files to load or can load a single file, e.g. x000.csv
      train: x[000..001]
      test: x[000..001]
      val: x[000..001]
    micro_batch_size: ${model.micro_batch_size}
    data_col: 1 # 0-based
    data_sep: ','
    header_lines: 1
    num_workers: 10
  seq_length: 1024 # maximum sequence length allowed

exp_manager:
  exp_dir: /tmp/nemo_experiments/megamolbart_pretrain
  create_wandb_logger: False
  create_tensorboard_logger: False
  wandb_logger_kwargs:
    offline: True

  # data:
  #   # PROJECT_MOUNT is env variable with root location of code e.g. /opt/nividia/bionemo or /workspace/bionemo
  #   links_file: ${oc.env:PROJECT_MOUNT}/examples/molecule/megamolbart/dataset/ZINC-downloader-test.txt # Set to ZINC-downloader-test.txt for demo
  #   dataset_path: /workspace/bionemo/data/zinc_csv/processed # parent directory for data, contains train / val / test folders. Needs to be writeable for index creation.
  #   dataset: # inclusive range of data files to load or can load a single file, e.g. x000 or x[000..186]
  #     train: x000 # Range is for full dataset
  #     test: x000
  #     val: x000