
ARG BIONEMO_IMAGE
FROM ${BIONEMO_IMAGE}

RUN pip install git+https://gitlab-master.nvidia.com/dl/gwe/torch_automated_profiler@abc09214
RUN mkdir -p -m 0700 ~/.ssh && ssh-keyscan gitlab-master.nvidia.com >> ~/.ssh/known_hosts || :

ARG TPL_REPO=ssh://git@gitlab-master.nvidia.com:12051/dl/gwe/torch_performance_linter
# FIXME [mgreaves] Security leak -- the gitlab CI will pass in a secret value (CI_JOB_TOKEN) into the
#                  TPL_REPO build argument. This means the secret is persisted in the image layers and
#                  viewable using `docker history`. Instead of fixing in [1], we've decided to punt on
#                  this since (a) it's not critical for the Jan 2023 bionemo release since customers do
#                  not get this image and (b) CI_JOB_TOKEN is a short lived, expiring token. By the time
#                  the image is built & pushed to the Gitlab container registry, the CI_JOB_TOKEN will
#                  expire. [2]
#                  
#
# The eventuial solution will need to look something like:
#
#    RUN --mount=type=ssh --mount=type=secret,id=TPL_REPO TPL_REPO=$(cat /run/secrets/TPL_REPO) pip install git+${TPL_REPO}
#
# Specifically, no more `ARG TPL_REPO` & mounting the entire TPL_REPO value as a secret.
#
# There is also a change in .gitlab-ci.yml that will need to take place as well. See that file for the FIXME comment.
#
# [1] https://gitlab-master.nvidia.com/clara-discovery/bionemo/-/merge_requests/645
# [2] https://docs.gitlab.com/ee/ci/jobs/ci_job_token.html
RUN --mount=type=ssh pip install git+${TPL_REPO}

RUN pip install jet-api --upgrade \
    --extra-index-url https://sc-hw-artf.nvidia.com/api/pypi/hw-joc-pypi/simple \
    --extra-index-url https://sc-hw-artf.nvidia.com/api/pypi/compute-pypi/simple

# TODO(trvachov): Fix this JET conflict. It seems that installing JET will downgrade pydantic.
RUN pip install pydantic==2.5.3
RUN pip install tabulate==0.9.0

COPY ./internal ${BIONEMO_HOME}/internal
COPY CONTRIBUTING.md ${BIONEMO_HOME}/
