
ARG BIONEMO_IMAGE
FROM ${BIONEMO_IMAGE}

RUN pip install git+https://gitlab-master.nvidia.com/dl/gwe/torch_automated_profiler@abc09214
RUN mkdir -p -m 0700 ~/.ssh && ssh-keyscan gitlab-master.nvidia.com >> ~/.ssh/known_hosts || :
ARG TPL_REPO=ssh://git@gitlab-master.nvidia.com:12051/dl/gwe/torch_performance_linter
RUN --mount=type=ssh pip install git+${TPL_REPO}


RUN pip install jet-api --upgrade \
    --extra-index-url https://sc-hw-artf.nvidia.com/api/pypi/hw-joc-pypi/simple \
    --extra-index-url https://sc-hw-artf.nvidia.com/api/pypi/compute-pypi/simple

# TODO(trvachov): Fix this JET conflict. It seems that installing JET will downgrade pydantic.
RUN pip install pydantic==2.5.3

COPY ./internal ${BIONEMO_HOME}/internal
COPY CONTRIBUTING.md ${BIONEMO_HOME}/
