FROM gitlab-master.nvidia.com:5005/dl/ai-services/python-clients/codeformat:latest
COPY setup/requirements-linter.txt /tmp/requirements-linter.txt
RUN pip3 install -r /tmp/requirements-linter.txt
# RUN pre-commit install
